### ISSUE TITLE
Rendering template to string causes error after updating to 1.0.0

### ISSUE THREAD

**Issue by KucharczykL** [wrabit/django-cotton#201]
# Version

After I updated to version 1.2.0 I am encountering an error with a template that used to work before (I tried different versions and the last working one is 0.9.40).

# Code

I have a custom Component function which renders a plain HTML tag or template (in this case a django-cotton template) to a string:

`button_test.py`
```py
button = Button(attributes = [], children = ["This is string node"])
```

And this is the code used:

`templates/cotton/button.html` (CSS omitted for clarity)
```django
<c-vars color="blue" size="base" />
<button type="button"
        title="{{ title }}"
                class="">
    {{ slot }}
</button>

```

`components.py`
```py
def Button(
    attributes: list[HTMLAttribute] = [],
    children: list[HTMLTag] | HTMLTag = [],
    size: str = "base",
    icon: bool = False,
    color: str = "blue",
):
    return Component(
        template="cotton/button.html",
        attributes=attributes + [("size", size), ("icon", icon), ("color", color)],
        children=children,
    )

HTMLAttribute = tuple[str, str | int | bool]
HTMLTag = str


def Component(
    attributes: list[HTMLAttribute] = [],
    children: list[HTMLTag] | HTMLTag = [],
    template: str = "",
    tag_name: str = "",
) -> HTMLTag:
    if not tag_name and not template:
        raise ValueError("One of template or tag_name is required.")
    if isinstance(children, str):
        children = [children]
    childrenBlob = "\n".join(children)
    if len(attributes) == 0:
        attributesBlob = ""
    else:
        attributesList = [f'{name}="{value}"' for name, value in attributes]
        # make attribute list into a string
        # and insert space between tag and attribute list
        attributesBlob = f" {" ".join(attributesList)}"
    tag: str = ""
    if tag_name != "":
        tag = f"<{tag_name}{attributesBlob}>{childrenBlob}</{tag_name}>"
    elif template != "":
        tag = render_to_string(
            template,
            {name: value for name, value in attributes}
            | {"slot": mark_safe("\n".join(children))},
        )
    return mark_safe(tag)
```

# Error

```
Error during template rendering

In template (snip)/templates/cotton/button.html, error at line 1
<c-vars /> tag must be used inside a component
1 	{% vars color="blue" size="base" %}
2 	<button type="button"
3 	        title="{{ title }}"
4 	                class="">
5 	    {{ slot }}
6 	</button>
7 	{% endvars %}
```

Local vars from Django Debug Toolbar:
```
context = [{'True': True, 'False': False, 'None': None}, {'size': 'base', 'icon': False, 'color': 'blue', 'slot': 'test', 'cotton_data': {'stack': [], 'vars': {}}}]
cotton_data = {'stack': [], 'vars': {}}
self = <django_cotton.templatetags._vars.CottonVarsNode object at 0x7f8fef616480>
```

**Comment by wrabit** [comment]
@KucharczykL thanks for the issue report, this was [mentioned a couple of days ago](https://github.com/wrabit/django-cotton/issues/182#issuecomment-2407897473), I'll put some priority into looking into this.

**Comment by wrabit** [comment]
@KucharczykL released a fix for this in [1.2.1](https://github.com/wrabit/django-cotton/releases/tag/v1.2.1), let me know if you still have issues.

**Comment by KucharczykL** [comment]
I have updated to 1.2.1 and I am getting a different error: `Invalid block tag on line 94: 'endblock', expected 'endc'. Did you forget to register or load this tag?`

The context:
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/tracker/game/377/view

Django Version: 5.1.2
Python Version: 3.12.5
Installed Applications:
['games.apps.GamesConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'template_partials',
 'graphene_django',
 'django_htmx',
 'django_cotton',
 'django_extensions',
 'django.contrib.admin',
 'debug_toolbar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_htmx.middleware.HtmxMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']


Template error:
In template /home/lukas/git/timetracker/games/templates/view_game.html, error at line 94
   Invalid block tag on line 94: 'endblock', expected 'endc'. Did you forget to register or load this tag?
   84 :             <div class="mb-6">
   85 :                 {% c h1 :badge="session_count>Sessions</c-h1" %}
   86 :                 {% c simple-table :rows="session_data.rows" :columns="session_data.columns" :header_action="session_data.header_action" :page_obj="session_page_obj" :elided_page_range="session_elided_page_range" %}{% endc %}
   87 :             </div>
   88 :         </div>
   89 :         <script>
   90 :         function getSessionCount() {
   91 :             return document.getElementById('session-count').textContent.match("[0-9]+");
   92 :         }
   93 :         </script>
   94 :      {% endblock content %} 
   95 : 

Traceback (most recent call last):
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ^^^^^^^^^^^^^^^^^^

During handling of the above exception ('endblock'), another exception occurred:
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/games/views/game.py", line 402, in view_game
    return render(request, "view_game.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django_cotton/templatetags/_component.py", line 133, in cotton_component
    nodelist = parser.parse(("endc",))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django_cotton/templatetags/_component.py", line 133, in cotton_component
    nodelist = parser.parse(("endc",))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django_cotton/templatetags/_component.py", line 133, in cotton_component
    nodelist = parser.parse(("endc",))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/git/timetracker/.venv/lib/python3.12/site-packages/django/template/base.py", line 563, in invalid_block_tag
    raise self.error(
    ^

Exception Type: TemplateSyntaxError at /tracker/game/377/view
Exception Value: Invalid block tag on line 94: 'endblock', expected 'endc'. Did you forget to register or load this tag?

```

**Comment by wrabit** [comment]
@KucharczykL block tags are not fully working alongside cotton. Cotton is really an alternative to using blocks altogether. I would recommend converting your usage of blocks to cotton components, for example https://django-cotton.com/docs/layouts.

**Comment by KucharczykL** [comment]
Thanks, I will do that! But the error message, docs or both should probably be changed in that case.

**Comment by wrabit** [comment]
@KucharczykL agreed + noted!

**Comment by KucharczykL** [comment]
Hi @wrabit, not sure if this is related but I also noticed that if I set a value inside a component to a default value using `<c-vars variable="value"/>` then it is not possible any more to override this variable when rendering the template to a string using `render_to_string("cotton/template.html", {"variable":"a new value"})`. The passed context is ignored.

**Comment by wrabit** [comment]
Hmm so yes, I think we will need a dedicated method such as `render_component` (as I think you said).
